### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by bewards** [rob-balfre/svelte-select#354]
I am using Svelte components in a "web component" kind of way on a .NET project, where regular svelte components are created with the Component API manually through my JavaScript:

**Loader File** - this file is imported directly into my main.js bundle. When the page loads, I'm able to create a Svelte component out of a **div** with a certain selector and pass down the props to the Svelte component (this has all been working well and I'm able to use Svelte store between components too):

``` js
import { attributesToObject } from '../../utilities/ElementHelpers';
import SiteLocationPicker, { selector } from './SiteLocationPicker.svelte';

// initiate svelte components
[...document.querySelectorAll<HTMLElement>(selector)].forEach(el => {
    new SiteLocationPicker({
        target: el,
        props: attributesToObject(el)
    });
});
```

**Svelte Component File**
``` svelte
<script context="module">
  export const selector = ".sl-picker__widget";
</script>

<script lang="ts">
  import Select from "svelte-select";

  export let placeholder: string = "";
  export let apiPath: string = "";

  let items = [
    {value: 'chocolate', label: 'Chocolate'},
    {value: 'pizza', label: 'Pizza'},
    {value: 'cake', label: 'Cake'},
    {value: 'chips', label: 'Chips'},
    {value: 'ice-cream', label: 'Ice Cream'},
  ];
</script>

<div class="sl-picker__widget-container">
  <h4>{apiPath}</h4>
  <h5>{placeholder}</h5>

  <Select {items} />
</div>
```

**Example html (from cshtml) file** - the "sl-picker__widget" gets transformed into a Svelte Component
``` html
<div class="sl-picker component">
    <div class="container">
        <h3 class="sl-picker__location-label">Site Location:</h3>
        <div class="sl-picker__widget" placeholder="Search Site Locations" api-path="/api/GetSiteLocations"></div>
    </div>
</div>
```

**Console Error**
![image](https://user-images.githubusercontent.com/3927169/142912580-0186fb8e-7b04-4916-b634-ccec33f93263.png)

**Gulp File w/ Rollup Configuration**
``` js
async function scripts() {
  const bundle = await rollup({
    input: "app/scripts/main.ts",
    plugins: [
      rollupReplace({
        'process.env.NODE_ENV': JSON.stringify('production'),
        'process.env.dev': isDev ? true : false,
        preventAssignment: false
      }),
      nodeResolve({
        browser: true
      }),
      typescript({
        rootDir: './app',
        sourceMap: !isProd,
        inlineSources: !isProd
      }),
      commonjs(),
      babel({
        include: [ 'app/**', 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' ], // only transpile our source code
        babelHelpers: 'bundled'
      }),
      svelte({
        // Tell the svelte plugin where our svelte files are located
        include: 'app/**/*.svelte',
        emitCss: false,
        preprocess: sveltePreprocess(),
        compilerOptions: {
            // customElement: true,
        }
      }),
    ]
  });
  
  // configure output bundle
  let outputBundleOptions = {
    file: argv.jsPath !== undefined ? `${__dirname}${argv.jsPath}` : '.tmp/scripts/main.js',
    format: "umd",
    name: 'app',
    sourcemap: true,
    plugins: [],
  };
  if (isProd) {
    outputBundleOptions.plugins.push(terser())
  }
  await bundle.write(outputBundleOptions);
  
  bundle.close().then(res => {
    server !== "undefined" && server.reload();
  });
  }
};
```

**package.json** - necessary dependencies
``` json
  "dependencies": {
    "@babel/runtime": "^7.14.0",
    "@babel/runtime-corejs3": "^7.14.0",
    "core-js": "^3.12.1",
    "postcss": "^8.3.6",
    "regenerator-runtime": "^0.13.7",
    "svelte-select": "^4.4.5",
  }
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/eslint-parser": "^7.15.4",
    "@babel/plugin-external-helpers": "^7.14.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.4",
    "@babel/register": "^7.15.3",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-commonjs": "^20.0.0",
    "@rollup/plugin-inject": "^4.0.2",
    "@rollup/plugin-node-resolve": "^13.0.4",
    "@rollup/plugin-replace": "^3.0.0",
    "@rollup/plugin-typescript": "^8.3.0",
    "@tsconfig/svelte": "^2.0.1",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "autoprefixer": "^10.3.4",
    "browser-sync": "^2.27.5",
    "cross-env": "^7.0.3",
    "cssnano": "^5.0.8",
    "del": "^6.0.0",
    "eslint": "^7.32.0",
    "eslint-plugin-import": "^2.25.2",
    "faker": "^5.5.3",
    "globby": "^11.0.3",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-better-rollup": "^4.0.1",
    "gulp-cli": "^2.3.0",
    "gulp-dart-sass": "^1.0.2",
    "gulp-data": "^1.3.1",
    "gulp-eslint": "^6.0.0",
    "gulp-filter": "^7.0.0",
    "gulp-if": "^3.0.0",
    "gulp-load-plugins": "^2.0.6",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^9.0.0",
    "gulp-size": "^4.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-uglify": "^3.0.2",
    "gulp-useref": "^5.0.0",
    "mkdirp": "^0.5.0",
    "rollup": "^2.58.0",
    "rollup-plugin-svelte": "^7.1.0",
    "rollup-plugin-terser": "^7.0.2",
    "svelte": "^3.44.2",
    "svelte-preprocess": "^4.9.8",
    "tslib": "^1.14.1",
    "typescript": "^4.4.3",
    "yargs": "^17.1.1"
  }
```

I cannot reproduce this on REPL due to the unique configuration, but I am happy to provide more information as requested.

**Update 1**
If I change the import to `import Select from "svelte-select/src/Select.svelte";` within my Svelte Component file, I receive the following error message on build:

```
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:158:30)
    at Module.error (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:12339:16)
    at Module.tryParse (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:12742:25)
    at Module.setSource (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:12645:24)
    at ModuleLoader.addModuleSource (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:22105:20)
    at ModuleLoader.fetchModule (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:22158:9)
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:22193:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (C:\source\Website\FED\node_modules\rollup\dist\shared\rollup.js:22169:9)
```

**Comment by rob-balfre** [comment]
@bewards hmmm not sure, maybe try updating your svelte rollup includes:
```js
include: ['app/**/*.svelte', 'node_modules/svelte-select/src/*.svelte']
```

**Comment by bewards** [comment]
Thanks @rob-balfre - this has resolved my issue (adding to svelte rollup plugin option)
